### ISSUE TITLE
Remove root `schedule:` nodes on suggested YML config

### ISSUE THREAD

**Issue by vinnicc** [moove-it/sidekiq-scheduler#112]
I got `no cron / every / at / in / interval found for schedule (schedule) - skipping` following the starting guide.

This trips new people as the recommended initializer will parse the YML expecting to find the individual job configs right away ([relevant line](https://github.com/moove-it/sidekiq-scheduler/blob/master/lib/sidekiq/scheduler.rb#L216)).

**Comment by DTrierweiler** [comment]
Same here. Should really be updated in the README.

**Comment by snmgian** [comment]
Thanks to @jsamos for fixing the README

**Comment by Mileshosky** [comment]
There are still references to :schedule: in the Readme, this tripped me up today.

**Comment by DaveSanders** [comment]
Still an issue... this also caused confusion with me today...

**Comment by snmgian** [comment]
`:schedule:` is the key to attach the schedule within `sidekiq.yml` config file: https://github.com/moove-it/sidekiq-scheduler#usage

If you are directly setting the schedule, or if you have the schedule in a different yml file: https://github.com/moove-it/sidekiq-scheduler#load-the-schedule-from-a-different-file

References to `:schedule:` in the Readme are in the context of `sidekiq.yml` file.

Feel free to re-open the issue if you think it's appropriate.

**Comment by shedd** [comment]
It's been a while since I've configured Sidekiq Scheduler and was also tripped up by this today.  I've always renamed the schedule file from the default to something with `schedule` in the name to make it easier to find.  I assume others are doing the same.

Would it make sense to raise a more specific error if the `:schedule:` root key is present with the alternate initializer?
