### ISSUE TITLE
Pure dynamic schedules not working, Schedule empty! Set Sidekiq.schedule

### ISSUE THREAD

**Issue by avongluck-r1soft** [moove-it/sidekiq-scheduler#125]
I'm playing with the idea of purely dynamic schedules... however the dynamic schedules never fire.

```
Scheduling environment polling job for -fa1b-4853... (set_schedule)
Scheduling environment polling job for -89c5-40a4... (set_schedule)
Scheduling environment polling job for -8367-4e06... (set_schedule)
(Sidekiq::Scheduler.reload_schedule!)
2016-08-26T18:38:07.849Z 10005 TID-7ltrg INFO: Reloading Schedule
2016-08-26T18:38:07.852Z 10005 TID-7ltrg INFO: Loading Schedule
2016-08-26T18:38:07.852Z 10005 TID-7ltrg INFO: Schedule empty! Set Sidekiq.schedule
2016-08-26T18:38:07.856Z 10005 TID-7ltrg INFO: Schedules Loaded
```

get_all_schedules shows the dynamic scheduled jobs... however they never fire and I see the error above.

init:
```
require 'sidekiq/scheduler'

Sidekiq.configure_server do |config|
  config.on(:startup) do
    Sidekiq::Scheduler.dynamic = true
  end
end
```

**Comment by artem-russkikh** [comment]
If you plan queue jobs from sidekiq thread, try to set dynamic in initializer like so

```ruby
# config/initializers/sidekiq_scheduler.rb

require 'sidekiq/scheduler'
Sidekiq::Scheduler.dynamic = true
```

I queue jobs only in Unicorn thread:

```ruby
# config/initializers/sidekiq_scheduler.rb

require 'sidekiq/scheduler'

Sidekiq::Scheduler.dynamic = true

if Rails.env.production? && (defined?(Rails::Server) || defined?(Unicorn))
  Sidekiq::Scheduler.enabled = true
  scheduler_options = {
    dynamic: true,
    enabled: true,
    schedule: nil,
    listened_queues_only: nil
  }
  schedule_manager = SidekiqScheduler::Manager.new(scheduler_options)
  schedule_manager.start
elsif Rails.env.test?
  Sidekiq::Scheduler.enabled = true
else
  Sidekiq::Scheduler.enabled = false
end
```

I mannualy start `SidekiqScheduler::Manager` to dynamicly fetch recurring jobs because this gem start `SidekiqScheduler::Manager` only in Sidekiq (by `Sidekiq.configure_server`) see https://github.com/moove-it/sidekiq-scheduler/blob/master/lib/sidekiq-scheduler.rb

**Comment by jcotillo** [comment]
i am having a similar issue. I set dynamic to true and added a new worker to scheduler.yml file after the server was running and it was not registered. I been playing around and i suspect scheduler manager is being initialized before the server config on startup block runs. Do not how to fix this without initializing another manager object after initialization like suggested  ^

**Comment by snmgian** [comment]
Hello @avongluck-r1soft 

As @artem-russkikh, `dynamic` flag must be set before startup. There was an error in README.md, it's fixed now, the following is just another way to set that flag:

```
Sidekiq.configure_server do |config|
  # This block only runs when sidekiq is running in server mode
  Sidekiq::Scheduler.dynamic = true
end
```

You can also specify that flag in `config/sidekiq.yml`
``` yml
:dynamic: true
```

How are you invoking `set_schedule`? Here's an example:
```ruby
Sidekiq.set_schedule(
  'bye', 
  { 
    class: 'ByeWorker', 
    cron: '20 * * * * *', 
    queue: 'high', 
    description: 'puts bye' 
  }
)
```

You should see an output like this in sidekiq logs:

```
2016-08-30T04:42:23.719Z 1843 TID-osohzpuxo INFO: Updating schedule
2016-08-30T04:42:23.721Z 1843 TID-osohzpuxo INFO: Scheduling bye {"class"=>"ByeWorker", "cron"=>"20 * * * * *", "queue"=>"high", "description"=>"puts bye"}
2016-08-30T04:42:23.721Z 1843 TID-osohzpuxo INFO: Schedules Loaded
2016-08-30T04:43:20.024Z 1843 TID-osohzpuxo INFO: queueing ByeWorker (bye)
2016-08-30T04:43:20.025Z 1843 TID-osohzxgvw ByeWorker JID-d7e3b0530edb4b38f6f8fbd4 INFO: start
bye
2016-08-30T04:43:20.025Z 1843 TID-osohzxgvw ByeWorker JID-d7e3b0530edb4b38f6f8fbd4 INFO: done: 0.0 sec
```

**Comment by avongluck-r1soft** [comment]
Thanks, i'll give that a try.  Any known performance hit of creating a large number of scheduled items?  I have a large database of objects (a few thousand) which need poll a REST url every 5 minutes for changes... thinking of creating a scheduled job for each item in the database.

**Comment by snmgian** [comment]
I think you should take into consideration two aspects: memory consumption and jobs execution time.

I made a test with `20_000` scheduled items, the memory usage went from `28MB` to `1.7GB` (it depends on the size of the schedule metadata you push with `set_schedule`). The jobs where pushed to sidekiq (`sidekiq-scheduler` is responsible only of pushing jobs into sidekiq) timely every 5 minutes. 

If you have a REST request/response cycle + a DB hit (a SQL UPDATE) of let's say **0.1 sec**, and you have 16 sidekiq workers, performing a batch 20_000 jobs will take 125 sec (number_of_jobs * job_time / number_of_workers). If the jobs take **0.5 sec** to complete, the whole batch will take 625 sec (10 min) so the next batch will be pushed into sidekiq in a timely manner but sidekiq will execute them with a delay of 5 min and so on (because is busy running the first batch).

You'll need to test your system in order to estimate how long it will take each batch and how much memory will be consumed, perhaps you could have cluster in order to split the workload. 

Have you thought of some other alternatives instead of having thousands of schedules?

**Comment by avongluck-r1soft** [comment]
My old model with resque was 5 workers chewing through a bunch of ActiveJobs.  I pass each database object as the argument to the ActiveJob via a task

```
task poll_things
  for each thing in database
   queue up new job (thing)
 end
end
```

```
cron every 5 minutes, rake things:poll_things
```

There really doesn't seem to be a way to do this via the scheduler as it operates on jobs directly (and there isn't a task layer to dynamically do multiple Jobs at a specified time.

**Comment by snmgian** [comment]
How about having one job running every 5 minutes, and that job will enqueue another job for each database object? 

```yml
:schedule:
   poll_things:
     every: ['5m']
     class: PollThingsWorker
     queue: high
```

``` ruby
class PollThingsWorker
  include Sidekiq::Worker

  def perform
    Thing.find_each do |thing| 
       RefresherWorker.perform_async( ... )
    end
  end
end
```

Having this will resemble your old approach. Instead of having a cron and a rake task, you'll have a cron via `sidekiq-scheduler` and a worker, that's the main motivation for sidekiq-scheduler: removing the combination of cron + command.

Instead of queueing a new job for every `thing`, you could send a batch of things to the job that makes the request to the REST API, I'm saying that because enqueing a job has some cost (it needs to send a command to Redis and then fetch the serialized job)

**Comment by snmgian** [comment]
Hello @avongluck-r1soft, do you have any update on this?
