### ISSUE TITLE
2.0.10 Causes Strong Params Errors

### ISSUE THREAD

**Issue by Petercopter** [moove-it/sidekiq-scheduler#140]
Upgraded from `2.0.08` to `2.0.10`, getting this error:

```
Failure/Error: params.require(:work_order).permit(:name, :description, customer_ids: [])
     
     NoMethodError:
       undefined method `each' for nil:NilClass
```
Something about the new version is causing problems with strong params.

**Comment by snmgian** [comment]
Hi @Petercopter 

Could you try it out branch `fix/symbol-config-keys`. 

If you are using bundler should point your Gemfile to that branch: 

```ruby
gem 'sidekiq-scheduler', git: 'https://github.com/moove-it/sidekiq-scheduler.git', branch: 'fix/symbol-config-keys'
```

Let me know if the fix solves the problem.

**Comment by snmgian** [comment]
Please upgrade to v2.0.11

**Comment by Petercopter** [comment]
@snmgian Thanks for the quick response. Something weird is happening with Rubygems.org. I see the 2.0.11 release there, but...

> Could not find gem 'sidekiq-scheduler (= 2.0.11)' in any of the gem sources listed in your Gemfile or available on this machine.

It also doesn't show up in `bundle outdated`.

Not sure what's going on. Will try again later.

**Comment by snmgian** [comment]
Running `gem install -v 2.0.11` worked as usual. It seems a problem related to bundler. I faced the same error as you using `bundler 1.13.2` and `1.13.1`

Using bundler `1.11.2` works as expected :|

Also, I yanked sidekiq-scheduler `v 2.0.11`, it's no longer available. 

I pushed v 2.0.12 (same code as v 2.0.11, I removed the old one before finding that the problem is more related to bundler) Please use v 2.0.12

**Comment by snmgian** [comment]
@Petercopter, it turned out that there's a problem with rubygems.org: https://status.rubygems.org/

If you run `bundle install --full-index` it will work. 

Use sidekiq-scheduler v `2.0.18`:) I just spent some release numbers making some testing.
