### ISSUE TITLE
Recent change has large implications for Sidekiq running on multiple machines

### ISSUE THREAD

**Issue by elskwid** [moove-it/sidekiq-scheduler#147]
We run `sidekiq-scheduler` as part of a multiple machine deployment in production. We recently upgraded from `2.0.8` to `2.0.18` and saw an issue where our schedules were being overwritten with an empty hash. [This change](https://github.com/moove-it/sidekiq-scheduler/commit/a96c776d882e2091b5deebc169cbc3ef7a663d85#diff-a5836faabd5ca942cf1c26ba8868bb6fR21) meant that our second server was emptying the schedule rather than ignoring the missing option.

This caused some fairly serious production issues which we've now fixed by disabling the scheduler in all environments by default and being explicit when we enable it.

Would it be useful to document this behavior in the README for future users? If you think so and you have a suggestion where that should go I will open a PR with the updates.

**Comment by danarnold** [comment]
This also happened to us, with a deployment of multiple sidekiq instances.

**Comment by snmgian** [comment]
At version <= 2.0.8 if the following config was given to a sidekiq-scheduler instance:

```yaml
:dynamic: true

:schedule:
  SomeWorker:
    every: '5s'
    class: SomeWorker
```

And then, if the config is changed, followed by a restart, to something like:

```yaml
:dynamic: true

:schedule:
  #SomeWorker:
    #every: '5s'
    #class: SomeWorker
```

sidekiq-scheduler will still push SomeWork into sidekiq for processing. 

The `dynamic` flag stores/reads from the schedule into/from Redis. So in this case, although the schedule was commented out, it was being read from Redis.

The intent of the change that @elskwid mentioned is to prevent that behavior.

In order to prevent purging the schedule stored in Redis, the `enable` flag could be set to false:

``` yaml
:enabled: false
```

@elskwid, @danarnold That behavior was documented here (recently): https://github.com/moove-it/sidekiq-scheduler/commit/a49fd5507b9a95cfabe1de03d1a925f8587d66ca

**Comment by danarnold** [comment]
What I'm confused about is why I'm getting an empty schedule at all. Maybe you can help.

This is in the app, inside our sidekiq initializer:
```ruby
Sidekiq.configure_server do |config|
  config.redis = { url: redis_url, namespace: namespace }
  schedule_file = 'config/schedule.yml'

  if File.exist?(schedule_file)
    Sidekiq.schedule = YAML.load_file(schedule_file)[Rails.env]
    Sidekiq::Scheduler.load_schedule!
  end
end
```

Then we simply initialize a few different servers with sidekiq and a few web servers.

**Comment by snmgian** [comment]
Hello @danarnold 

- Could you post here the standard output of the sidekiq startup?
- Could you post here the contents of 'config/schedule.yml'  ?
- Do all the servers run within the same Rails.env?
- In case they are running with different Rails environments, each env has it's own redis / redis namespace ?
- Are you using Active Job for your jobs?

**Comment by danarnold** [comment]
Here is the output of startup on 2.0.19: https://gist.github.com/danarnold/49b557863f2f87c69b948e9f137fef8e
Here is the output of startup on 2.0.8: https://gist.github.com/danarnold/e24d00f8306aa305499ee55b05ecbabf

Here is the contents of config/schedule.yml with all of the worker names changed (they are all different in our actual app): https://gist.github.com/danarnold/94f3d3a9f748c004891806859a1d82a6

The servers do all run with the same Rails.env, yes. They all are set to "production" in a fairly standard production configuration. We use separate Redis instances for different environments, like our staging environment.

We are not using ActiveJob.

**Comment by snmgian** [comment]
Hi @danarnold 

Could you verify that the line `Sidekiq.schedule = YAML.load_file(schedule_file)[Rails.env]` in `initializers/sidekiq.rb` is actually being executed?

I'm asking that because when `dynamic` flag is `true`, then the scheduler loads the configuration from Redis. When version `>= 2.0.9`, it also empties the configuration stored in Redis during startup (if local config is empty).

By looking at your logs, I see the message "SidekiqScheduler is disabled", so if sidekiq-scheduler, no matter which version is being used, tries to load the schedule is because it's being re-enabled somewhere. Is there some place in your code in which you are doing smth like?: 

```ruby
Sidekiq::Scheduler.enabled = true
```

**Comment by danarnold** [comment]
The initializer is definitely being executed. (The code did not change in any way between the above examples. The only thing that changed was the version of sidekiq-scheduler that was being run.) Our configuration is basically an even simpler version of what's specified in the README, with Sidekiq::Scheduler being loaded in the `Sidekiq.configure_server` block, which all runs inside the `config/initializers/sidekiq.rb` file.

The initializer is the only place where we run any code on the Sidekiq or Sidekiq::Scheduler classes. I too noticed the message saying "SidekiqScheduler is disabled, and I have no idea why it would say that, since we do not have any code that sets `Sidekiq::Scheduler.enabled`.

**Comment by snmgian** [comment]
"SidekiqScheduler is disabled" message is printed out when `Sidekiq::Scheduler.enabled` is false. Another way to configure that flag is by having this:

```yaml
# config/sidekiq.yml
:enabled: false
```

With version `2.0.8`, if the schedule config was stored in Redis it will load even if the initializer didn't execute.

I setup a Rails app with pretty much the same sidekiq initializer as you. I'm able load the schedule using 2.0.8 and then loading an empty schedule using 2.0.19. But I'm not able to disable the scheduler, get the message printed out, and then to load the schedule in the same sequence order as your logs show.

**Comment by danarnold** [comment]
It's strange that it's displaying that message, yeah. I was confused when I first noticed it, too, but didn't worry too much about it since our schedules were being loaded. We don't have a `config/sidekiq.yml` file at all, by the way.

I should note that if I switch back to 2.0.8 after the schedules have been cleared by the higher version, the next load of sidekiq will successfully load all of the schedules. This, to me, makes it clear that the schedules should be loading successfully and that there aren't issues in the loading code - because if they were cleared by >2.0.8, they wouldn't have been able to have been loaded from Redis.

**Comment by snmgian** [comment]
Do you have this in your Gemfile?

``` ruby
gem 'sidekiq-scheduler', '2.0.19', require: false
```

If so, could you remove the `require: false` option? I was able to reproduce the problem you mention by  having that option set to false.

It you are not able to remove that option, could you try by requiring sidekiq-scheduler at the top of your sidekiq initializer? That should work too

```ruby
require 'sidekiq-scheduler'
```

**Comment by danarnold** [comment]
We don't have `require: false` in our initializer.

I tried that require line anyway, and require returned false indicating that it was already required, and I still get the disabled message when starting sidekiq.

**Comment by elskwid** [comment]
@danarnold Our logs looked a lot like yours. My poking around when we hit our issue showed that the `Sidekiq.schedule` is not used during initialization. 

Take a look [where the schedule is set](https://github.com/moove-it/sidekiq-scheduler/blob/29bc71d22b525ca7b717970dfb30c275edf82e82/lib/sidekiq-scheduler.rb#L24). Both `dynamic` and `enabled` use the class methods or the config value. The `schedule` setting is unique in that it only uses the config value. Which [leads to an empty schedule on boot](https://github.com/moove-it/sidekiq-scheduler/blob/29bc71d22b525ca7b717970dfb30c275edf82e82/lib/sidekiq/scheduler.rb#L61) as the message in your log shows. Then, load a schedule, assign it, and call `load_schedule!` which displays the "schedules loaded" message.

The change that prompted me to file the issue assigned `options[:schedule]` to `Sidekiq.schedule` or [an empty hash](https://github.com/moove-it/sidekiq-scheduler/blob/994efc454954868349a522e345bda488a9352bca/lib/sidekiq-scheduler/manager.rb#L21) and thus we see empty schedules on some servers.

My workaround was to change the initializer to:
* be much more explicit
* always load the schedule
* conditionally enable the scheduler

Here's a shortened version:

```ruby
# requires...

# Scheduler default configuration
Sidekiq::Scheduler.enabled = false
Sidekiq::Scheduler.dynamic = false

schedule_config = Rails.root.join("config/sidekiq_schedule.yml")
schedule = YAML.load_file(schedule_config)[Rails.env] || {}

# Set the schedule outside the config block
Sidekiq.schedule = schedule

# server config
Sidekiq.configure_server do |config|
  # Make schedule available to the SidekiqScheduler::Manager during initialize
  #
  # Due to a twist in the logic during the SidekiqScheduler boot sequence
  # `Sidekiq.schedule` gets overwritten with the value of `options[:schedule]`
  # which means it has the same value but this makes it available to us outside
  # the server configuration and takes advantage of the manager boot to
  # avoid the need to reload the schedule after it's found to be empty.
  config.options[:schedule] = Sidekiq.schedule

  # Scheduler enabled in non-prod environments or on a single server in prod
  if !Rails.env.production? || ENV["SERVER_NAME"] == "our-server-name"
    Sidekiq::Scheduler.enabled = true
  end
end
```

**Comment by snmgian** [comment]
I just found the way to reproduce the issue @danarnold describes. In my previous setup I used the `:startup` hook, when in fact the examples provided here directly passed the configuration block to `configure_server`

I just pushed some changes to branch `issue/147`, could you guys give it a try by setting this in your Gemfile?:

```ruby
gem 'sidekiq-scheduler', git: 'https://github.com/moove-it/sidekiq-scheduler.git', branch: 'issue/147'
# run `bundle` after changing the Gemfile
```

I tested different scenarios and it would be awesome if you can test the fix within your apps

**Comment by danarnold** [comment]
That branch works for me, I started sidekiq and see the schedules being loaded successfully.

**Comment by snmgian** [comment]
@elskwid  did you have a chance to test `issue/147` branch? The plan is to release tomorrow. Thanks

**Comment by elskwid** [comment]
@snmgian I can't actually test in an environment like our production environment but I will make time to roll it out as soon as you have an update. Sorry, but our other envs aren't quite the same. (Not yet anyways). 😄
