### ISSUE TITLE
*Need Advice* Sidekiq jobs eat memory !

### ISSUE THREAD

**Issue by zauzaj** [moove-it/sidekiq-scheduler#211]
I'd like to optimize my notification system, so here is how it works now:

Every time some change occurred on application, we're calling background job (Sidekiq) in order to compute some values and then to notify users via email.

This approach worked very well for a while, but suddenly we got memory leak as there were a lot of actions very frequently and we had about 30-50 workers per second so I need to refactor this.

What I would like to do is, instead of running worker immediately, to use sidekiq-scheduler but I'm afraid that also will cause a problem, but just "delayed" problem.

I'd like to hear from you if sidekiq-scheduler is good way for this or there is some other possible way to solve this issue?

Thanks in advice !

**Comment by snmgian** [comment]
Hi @zauzaj ,

I think the first thing to do is to find what is causing high memory consumption. 

You could setup a test environment for yourself, fire up those workers in the same way the app does it, and then measure how much memory is consumed. 

Depending on the implementation of Ruby (MRI, JRuby, Rubinius, ...) you are using you can use some profiler or some others, or you can just run `top`, `htop` commands or use gnuplot + ps to generate a chart.

A profiler will help you find which method/class/objects has consumed most memory, and based on that info you'll be in a better position to spot what's part of the code that needs attention. 

If you are just using `ps`, `htop` or similars, you could comment part of the code, run the test again and so on until you find which part of the code causes that high memory consumption.

For example, maybe the app is loading a bunch of ActiveRecord objects that you don't need, eager loading some association that you only need if some condition is met, or maybe there's a growing array that never gets freed.

If there's nothing that you can do at app side (for example, you are loading into memory only what you need) you could try some other things. like: Running sidekiq in a separate server, running more than one sidekiq instance, decreasing the number of concurrent workers (because each worker runs a job that consumes memory). The latter option will cause to some of your notification be delayed a bit, so it depends on whether that's acceptable for the app or not.

sidekiq-scheduler will help you under a different approach: Store somewhere (DB, redis) which actions need to be computed and notified, and then have sidekiq-scheduler to run ONE job every 10 minutes (for example) that takes those actions (maybe using a `find_each` if you are using ActiveRecord for example), compute, notify and mark the action as processed.

First, try to find where the problem is. Then fix it. If there's no possible under your current approach then change your approach to process a batch of actions using sidekiq-scheduler, or add more processing power spread over multiple server (more sidekiq instances for example).

Hope that helps.

**Comment by zauzaj** [comment]
@snmgian Thanks a bunch for detailed explanation :) I'm already on investigating where is the `bottleneck`. 

Thanks again.
