### ISSUE TITLE
How to retrieve the last run time

### ISSUE THREAD

**Issue by davidjnorth** [moove-it/sidekiq-scheduler#230]
Is there a way to get a job's last run time in order to use it my logic? ie. Get all records where created_at > last_run_time?

Currently I've setup my job to run once an hour and then use `last_run_time = Time.now - 1.hour`, but its not full proof eg. if the job fails and needs to be rerun.

**Comment by snmgian** [comment]
Hi @davidjnorth 

Take a look at https://github.com/moove-it/sidekiq-scheduler#schedule-metadata, `:scheduled_at` is a Float (see https://ruby-doc.org/core-2.3.0/Time.html#method-i-to_f), and represents the timestamp at which the job was scheduled to be pushed to sidekiq.

That is more accurate than doing `Time.now` inside your sidekiq job's `#perform` method. So, you could do `Time.at(metadata[:scheduled_at]) - 1.hour`

As far as I understand, you are trying to get the records that you didn't process yet. Relying in `created_at` could lead to some problems in case you have more than one server doing `SomeModel.create(...)` because their clocks can be out of sync ...

When dealing with that use case I ended up having a column of boolean type in the model's table that is updated to `true` when the record is processed.

Another option, in case you have a sequential ID for that table, is to store somewhere the last processed ID, obtain that ID at the beginning of the job and then query for `"id > ?"`.

**Comment by davidjnorth** [comment]
Thanks for the response @snmgian 

I looked through the gem and found this `SidekiqScheduler::RedisManager.get_job_last_time(name)`. This is essentially what I was looking for, although I did not end up using it because it gets updated even if the job fails, and does not update when "Enqueue now" is clicked on the sidekiq dashboard.

I ended up storing the last_successfully_run_time myself and then using and updating that where necessary. I see your concern about doing it in this way due to the clocks being out of sync so I may change to the boolean solution.

Thanks for the input.
