### ISSUE TITLE
Rails Model is not recognized into perform method

### ISSUE THREAD

**Issue by RuanHerculano** [moove-it/sidekiq-scheduler#236]
Im create the directory `app/workers`, and create into directory the file `clean_posts.rb`.
Right after, add the down code for this file.
  
```ruby
# app/workers/clean_posts.rb
class CleanPosts
  include Sidekiq::Worker
  # sidekiq_options :queue => :background

  def perform
    # Post model is not recognized
    # Error: "WARN: NameError: uninitialized constant Post"
    ::Post.recent.destroy_all
  end
end
```

Import the created directory.
```ruby
# config/application.rb
config.autoload_paths << Rails.root.join('app', 'workers')
```
Run with this command:
`bundle exec sidekiq -r ./app/workers/clean_posts.rb`

And the following error happened:
`WARN: NameError: uninitialized constant Post `

**Comment by rrrcompagnoni** [comment]
You might not need to set `workers` path on autoload_paths, I think Rails already do it for you.
Also, removing `::` before your Post class call, what does it happen?

**Comment by snmgian** [comment]
Hi @RuanHerculano,

As @rrrcompagnoni  said, you don't need to include `workers` into autoload paths array. 

The issue here is that you are passing in the `-r` option. When you pass in a file for that option, sidekiq doesn't loads Rails, it just requires the file you passed in. So, as Rails is not being loaded, the rails app doesn't start, and your models are also not loaded, that's why the `NameError` occurs.

Remove the `-r` option, and also remove the `::` as it's not needed, unless you have smth in `CleanPosts::Post`, but I think you don't have that.
