### ISSUE TITLE
No next execution for this job

### ISSUE THREAD

**Issue by bengg** [moove-it/sidekiq-scheduler#243]
I am trying to enqueue a job with the following parameters ["1h", {"first_at"=>"2018-02-09T19:25:00+01:00", "last_at"=>"2018-02-09T22:55:00+01:00"}]
But it shows "No next execution for this job" 
It is the "first_at" not the right parameter?

This is how it shows on the Web UI: 
![captura de pantalla 2018-02-09 a las 19 11 36](https://user-images.githubusercontent.com/2690298/36066002-04b0ad70-0ea3-11e8-98ef-209486fadb39.png)

**Comment by snmgian** [comment]
Hi @bengg 

`first_at` is the parameter name you have to use. 

It seems the `first_at` value is previous to current time. Look for this in your logs:

```
2018-02-13T00:54:43.413Z 9627 TID-grldt85mo WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"startup"}
2018-02-13T00:54:43.413Z 9627 TID-grldt85mo WARN: ArgumentError: cannot set first[_at|_in] in the past: "2018-02-13T01:54:00+01:00" -> #<EtOrbi::EoTime:0x005609d9b47330 @seconds=1518483240.0, @zone=#<TZInfo::DataTimezone: +01:00>, @time=nil>
```

You should set first_at to a point in the future.

I don't know what your use case is. Maybe you'll need to set your schedule in a programmatic way, instead of using a config file. Take a look at https://github.com/moove-it/sidekiq-scheduler#load-the-schedule-from-a-different-file, and https://github.com/moove-it/sidekiq-scheduler#dynamic-schedule to get some ideas.

**Comment by snmgian** [comment]
Hi @bengg, do you have any update on this?

**Comment by bengg** [comment]
Hi @snmgian thank you for the quick reply. 
Finally I used "first_in" instead of "first_at" and works as expected.
