### ISSUE TITLE
Running a Rake task in the Perform method

### ISSUE THREAD

**Issue by chrisatboilerjuice** [moove-it/sidekiq-scheduler#327]
Hi there!

I'm trying to run a rake task inside the perform method in the scheduler.rb example below:

`require 'sidekiq-scheduler'
require 'rake'

class Sitemap
  include Sidekiq::Worker

  def perform
    Rake::Task['sitemap:refresh'].invoke
  end
end`

I've had the write the rake task in this format otherwise the code complains it doesn't know what rake is. So now the code doesn't complain about the rake it now complains that the task doesn't exist when it 100% does exist. Any ideas what the problem is? 

Thanks, Chris

**Comment by bpo** [comment]
@chrisatboilerjuice It sounds like you're missing a way to load the rest of your project's environment. Typically that scheduled job would execute the same shared library as a Rake task rather than executing Rake directly.

But anyway, unrelated to sidekiq-scheduler: if you just need to load a local Rakefile, you can do that with `load('Rakefile')`, and you can check which tasks are loaded with something like `p Rake.application.tasks.map(&:name)`.

**Comment by chrisatboilerjuice** [comment]
@bpo Thanks for the reply. I'll give this a go see how I get on.
